name: kanban_flt
description: A Kanban Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: any
  
  get:
  dropdown_button2: ^2.3.8

  loading_animation_widget:
  kanban_board:
  appflowy_board:
  english_words: ^4.0.0
  provider: ^6.0.0
  settings_ui: ^2.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_core: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
