// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDifrJSZJXjXVnr5tkKGneEBSkAyI6X4J4',
    appId: '1:279286220681:android:6eb0014421b0534a330358',
    messagingSenderId: '279286220681',
    projectId: 'kaban-flt',
    databaseURL: 'https://kaban-flt-default-rtdb.firebaseio.com',
    storageBucket: 'kaban-flt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdLYpn1eotBiVNafo7iaNpSABopUsmBM',
    appId: '1:279286220681:ios:987782a670f8217d330358',
    messagingSenderId: '279286220681',
    projectId: 'kaban-flt',
    databaseURL: 'https://kaban-flt-default-rtdb.firebaseio.com',
    storageBucket: 'kaban-flt.appspot.com',
    iosClientId:
        '279286220681-a26a8uupdqhjslj7tuup26sgo155875t.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanbanFlt',
  );
}
